name: mightystore
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^4.4.14

  # BASE
  intl: 0.17.0

  # FIREBASE PACKAGES
  firebase_crashlytics: ^2.5.3
  firebase_analytics: ^9.1.2
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  firebase_remote_config: ^2.0.2

  # UI
  flutter_vector_icons: ^1.0.0
  dotted_border: ^2.0.0+1
  flutter_rating_bar: ^4.0.0
  otp_text_field: ^1.1.2
  flutter_staggered_grid_view: ^0.4.1
  country_code_picker: ^2.0.2
  html: ^0.15.0
  flutter_html: ^2.2.1
  package_info: ^2.0.2
  clippy_flutter: 2.0.0-nullsafety.1

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.3.0

  # STATE MANAGEMENT
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

  # ADS
  google_mobile_ads: ^1.1.0

  # VIDEOS
  video_player: ^2.3.0

  # IMAGES
  image_picker: ^0.8.4+11
  cached_network_image: ^3.2.0
  photo_view: ^0.13.0

  # AUTHENTICATION
  google_sign_in: ^5.2.4
  the_apple_sign_in: ^1.1.1

  # CONNECTIVITY
  http: ^0.13.4
#  connectivity: ^3.0.6
  share: ^2.0.4

  #TOOLS
  google_fonts: ^2.3.1

  # WEB TOOLS
  webview_flutter: ^2.3.1

  # PAYMENTS
  flutter_stripe: ^2.4.0
  razorpay_flutter: ^1.2.9
  flutterwave_standard: ^1.0.3
  flutter_paystack: ^1.0.5+1

  # LAUNCH URL
  url_launcher: ^6.0.20

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/mightystore/
    - lang/
    - assets/
    - images/mightystore/Christmas/
    - images/mightystore/Halloween/
